@WebApplicationTestLongPooling_HostAddress = http://localhost:5000

POST {{WebApplicationTestLongPooling_HostAddress}}/AddMessage
Accept: application/json
Content-type: application/json

{
    "Ñhannel" : "channel1",
    "Message" : "-22-",
    "User" : "user1"
}

###

Get {{WebApplicationTestLongPooling_HostAddress}}/LoongPooling/test
Accept: text/message
